version: "3.3"

services:
  server:
    build: .
    restart: on-failure  
    command: sh -c "python main.py"
    ports:
      - "5000:5000"
    volumes:
      - '.:/app'
    working_dir: /app
    tty: true
