name: Auto bump version

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  # If pull request was merged then we should check for a package version update
  check-for-no-version-changing:
    runs-on: ubuntu-latest
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Get package new version name
      - name: Get package info
        id: packageNew
        uses: codex-team/action-nodejs-package-info@v1

      # Checkout to the base commit before merge
      - name: Checkout to the base commit before merge
        run: git checkout ${{ github.event.pull_request.base.sha }}

      # Get package old version name
      - name: Get package info
        id: packageOld
        uses: codex-team/action-nodejs-package-info@v1

      # Stop workflow and do not bump version if it was changed already
      - name: Stop workflow and do not bump version if it was changed already
        uses: actions/github-script@v3
        if: steps.packageOld.outputs.version != steps.packageNew.outputs.version
        with:
          script: |
            core.setFailed('Version was changed! ${{ steps.packageOld.outputs.version }} -> ${{ steps.packageNew.outputs.version }}')

  bump-version:
    needs: check-for-no-version-changing
    runs-on: ubuntu-latest
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v2

      # Setup node environment
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      # Bump version to the next prerelease (patch) with rc suffix
      - name: Suggest the new version
        run: yarn version --prerelease --preid rc --no-git-tag-version

      # Get package new version name
      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1

      # Commit and push changes
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Bump version up to ${{ steps.package.outputs.version }}"